# Mod Info
p_name = Cosmic Tools
p_id = cosmic_tools
p_group = com.darkmattrmaestro.cosmic_tools
p_desc = Tools for Cosmic Reach
p_author = DarkMattrMaestro
p_version = 0.0.3

# Cosmic Reach
cosmic_reach_version = 0.5.24-alpha

# Puzzle Loader
puzzle_loader_cosmic_version = 1.7.2-alpha
puzzle_loader_core_version = 1.4.1-alpha

# Cosmic API
cosmic_api_version = 1.4.3-0.5.21

# Puzzle Gradle
puzzle_jigsaw_suite = 1.4.0-beta

org.gradle.daemon = false

itch_api_key = aaaaaaaaaaaaaaaaaaaaaaa