# Mod Info
p_name = Cosmic Tools
p_id = cosmic_tools
p_group = com.darkmattrmaestro.cosmic_tools
p_desc = Tools for Cosmic Reach
p_author = DarkMattrMaestro
p_version = 0.0.5

# Cosmic Reach
cosmic_reach_version = 0.6.1-alpha

# Puzzle Loader
puzzle_loader_cosmic_version = 1.7.5-alpha
puzzle_loader_core_version = 1.4.1-alpha

# Cosmic API
cosmic_api_version = 1.4.6-0.5.25

# Puzzle Gradle
puzzle_jigsaw_suite = 1.4.0-beta

# ImGui
imgui_integration_version = 0.6.1-1.0.6

# OpenCV
opencv_version = 4.9.0-0

itch_api_key = aaaaaaaaaaaaaaaaaaaaaaa